/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    CardTemplate: typeof import('./src/components/templates/CardTemplate/index.vue')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    Image: typeof import('primevue/image')['default']
    ResumeAvatar: typeof import('./src/components/ResumeAvatar.vue')['default']
    ResumeEditor: typeof import('./src/components/ResumeEditor.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SimpleTemplate: typeof import('./src/components/templates/SimpleTemplate/index.vue')['default']
    Slider: typeof import('primevue/slider')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
  }
}
