/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    CardTemplate: typeof import('./src/components/templates/CardTemplate/index.vue')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    Edit: typeof import('./src/components/Edit.vue')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    Form: typeof import('@primevue/forms/form')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Message: typeof import('primevue/message')['default']
    PdfViewer: typeof import('./src/components/PdfViewer.vue')['default']
    SimpleTemplate: typeof import('./src/components/templates/SimpleTemplate/index.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
  }
}
